# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  cv_config = debug

else ifeq ($(config),release)
  cv_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := cv

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

cv:
ifneq (,$(cv_config))
	@echo "==== Building cv ($(cv_config)) ===="
	@${MAKE} --no-print-directory -C . -f cv.make config=$(cv_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f cv.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   cv"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"